export const techMap: { [key: string]: string } = {
  javascript: "devicon-javascript-plain",
  js: "devicon-javascript-plain",
  typescript: "devicon-typescript-plain",
  ts: "devicon-typescript-plain",
  react: "devicon-react-original",
  reactjs: "devicon-react-original",
  nextjs: "devicon-nextjs-plain",
  next: "devicon-nextjs-plain",
  nodejs: "devicon-nodejs-plain",
  node: "devicon-nodejs-plain",
  bun: "devicon-bun-plain",
  bunjs: "devicon-bun-plain",
  deno: "devicon-denojs-original",
  denojs: "devicon-denojs-plain",
  python: "devicon-python-plain",
  java: "devicon-java-plain",
  "c++": "devicon-cplusplus-plain",
  cpp: "devicon-cplusplus-plain",
  "c#": "devicon-csharp-plain",
  csharp: "devicon-csharp-plain",
  php: "devicon-php-plain",
  html: "devicon-html5-plain",
  html5: "devicon-html5-plain",
  css: "devicon-css3-plain",
  css3: "devicon-css3-plain",
  git: "devicon-git-plain",
  docker: "devicon-docker-plain",
  mongodb: "devicon-mongodb-plain",
  mongo: "devicon-mongodb-plain",
  mysql: "devicon-mysql-plain",
  postgresql: "devicon-postgresql-plain",
  postgres: "devicon-postgresql-plain",
  aws: "devicon-amazonwebservices-original",
  "amazon web services": "devicon-amazonwebservices-original",
  firebase: "devicon-firebase-plain",
  graphql: "devicon-graphql-plain",
  vue: "devicon-vuejs-plain",
  vuejs: "devicon-vuejs-plain",
  tailwind: "devicon-tailwindcss-plain",
  tailwindcss: "devicon-tailwindcss-plain",
  angular: "devicon-angularjs-plain",
  jquery: "devicon-jquery-plain",
  sass: "devicon-sass-plain",
  laravel: "devicon-laravel-plain",
  rails: "devicon-rails-plain",
  ruby: "devicon-rails-plain",
  redis: "devicon-redis-plain",
  linux: "devicon-linux-plain",
  jenkins: "devicon-jenkins-plain",
  kubernetes: "devicon-kubernetes-plain",
  azure: "devicon-azure-plain",
  "azure devops": "devicon-azure-plain",
  gcp: "devicon-googlecloud-plain",
  "google cloud": "devicon-googlecloud-plain",
  bitbucket: "devicon-bitbucket-plain",
  nginx: "devicon-nginx-plain",
  blender: "devicon-blender-plain",
  unity: "devicon-unity-original",
  unreal: "devicon-unrealengine-original",
  swift: "devicon-swift-plain",
  kotlin: "devicon-kotlin-plain",
  go: "devicon-go-plain",
  rust: "devicon-rust-plain",
  dart: "devicon-dart-plain",
  flask: "devicon-flask-original",
  django: "devicon-django-plain",
  bootstrap: "devicon-bootstrap-plain",
  materialui: "devicon-materialui-plain",
  "material ui": "devicon-materialui-plain",
  photoshop: "devicon-photoshop-plain",
  illustrator: "devicon-illustrator-plain",
  xd: "devicon-xd-plain",
  premiere: "devicon-premiere-plain",
  figma: "devicon-figma-plain",
  inkscape: "devicon-inkscape-plain",
  trello: "devicon-trello-plain",
  jira: "devicon-jira-plain",
  heroku: "devicon-heroku-plain",
  elasticsearch: "devicon-elasticsearch-plain",
  redux: "devicon-redux-original",
  threejs: "devicon-threejs-original",
  c: "devicon-c-plain",
  scala: "devicon-scala-plain",
  r: "devicon-r-plain",
  matlab: "devicon-matlab-plain",
  julia: "devicon-julia-plain",
  haskell: "devicon-haskell-plain",
  elixir: "devicon-elixir-plain",
  erlang: "devicon-erlang-plain",
  clojure: "devicon-clojure-plain",
  lua: "devicon-lua-plain",
  perl: "devicon-perl-plain",
  groovy: "devicon-groovy-plain",
  objectivec: "devicon-objectivec-plain",
  assembly: "devicon-assembly-plain",
  fortran: "devicon-fortran-plain",
  cobol: "devicon-cobol-plain",
  pascal: "devicon-pascal-plain",
  prolog: "devicon-prolog-plain",
  scheme: "devicon-scheme-plain",
  ocaml: "devicon-ocaml-plain",
  fsharp: "devicon-fsharp-plain",
  vbnet: "devicon-vbnet-plain",
  actionscript: "devicon-actionscript-plain",
  coffeescript: "devicon-coffeescript-plain",
  livescript: "devicon-livescript-plain",
  crystal: "devicon-crystal-plain",
  nim: "devicon-nim-plain",
  v: "devicon-v-plain",
  zig: "devicon-zig-plain",
  odin: "devicon-odin-plain",
  carbon: "devicon-carbon-plain",
  bicep: "devicon-bicep-plain",
  solidity: "devicon-solidity-plain",
  vyper: "devicon-vyper-plain",
  move: "devicon-move-plain",
  circom: "devicon-circom-plain",
  cairo: "devicon-cairo-plain",
  fe: "devicon-fe-plain",
  motoko: "devicon-motoko-plain",
  sway: "devicon-sway-plain",
  yul: "devicon-yul-plain",
  less: "devicon-less-plain",
  stylus: "devicon-stylus-plain",
  webpack: "devicon-webpack-plain",
  babel: "devicon-babel-plain",
  gulp: "devicon-gulp-plain",
  grunt: "devicon-grunt-plain",
  rollup: "devicon-rollup-plain",
  vite: "devicon-vite-plain",
  parcel: "devicon-parcel-plain",
  browserify: "devicon-browserify-plain",
  jasmine: "devicon-jasmine-plain",
  jest: "devicon-jest-plain",
  mocha: "devicon-mocha-plain",
  karma: "devicon-karma-plain",
  cypress: "devicon-cypress-plain",
  selenium: "devicon-selenium-plain",
  playwright: "devicon-playwright-plain",
  puppeteer: "devicon-puppeteer-plain",
  storybook: "devicon-storybook-plain",
  docusaurus: "devicon-docusaurus-plain",
  gatsby: "devicon-gatsby-plain",
  nuxtjs: "devicon-nuxtjs-plain",
  angularjs: "devicon-angularjs-plain",
  ember: "devicon-ember-plain",
  backbone: "devicon-backbone-plain",
  dojo: "devicon-dojo-plain",
  extjs: "devicon-extjs-plain",
  sencha: "devicon-sencha-plain",
  knockout: "devicon-knockout-plain",
  aurelia: "devicon-aurelia-plain",
  polymer: "devicon-polymer-plain",
  svelte: "devicon-svelte-plain",
  alpinejs: "devicon-alpinejs-plain",
  lit: "devicon-lit-plain",
  stencil: "devicon-stencil-plain",
  preact: "devicon-preact-plain",
  inferno: "devicon-inferno-plain",
  mithril: "devicon-mithril-plain",
  marko: "devicon-marko-plain",
  ractive: "devicon-ractive-plain",
  riot: "devicon-riot-plain",
  canjs: "devicon-canjs-plain",
  flight: "devicon-flight-plain",
  marionette: "devicon-marionette-plain",
  chaplin: "devicon-chaplin-plain",
  thorax: "devicon-thorax-plain",
  spine: "devicon-spine-plain",
  batman: "devicon-batman-plain",
  sammy: "devicon-sammy-plain",
  cappuccino: "devicon-cappuccino-plain",
  sproutcore: "devicon-sproutcore-plain",
  yui: "devicon-yui-plain",
  mootools: "devicon-mootools-plain",
  prototype: "devicon-prototype-plain",
  scriptaculous: "devicon-scriptaculous-plain",
  express: "devicon-express-plain",
  nestjs: "devicon-nestjs-plain",
  fastify: "devicon-fastify-plain",
  koa: "devicon-koa-plain",
  hapi: "devicon-hapi-plain",
  sails: "devicon-sails-plain",
  loopback: "devicon-loopback-plain",
  strapi: "devicon-strapi-plain",
  keystonejs: "devicon-keystonejs-plain",
  ghost: "devicon-ghost-plain",
  hexo: "devicon-hexo-plain",
  jekyll: "devicon-jekyll-plain",
  hugo: "devicon-hugo-plain",
  eleventy: "devicon-eleventy-plain",
  metalsmith: "devicon-metalsmith-plain",
  wintersmith: "devicon-wintersmith-plain",
  harp: "devicon-harp-plain",
  roots: "devicon-roots-plain",
  middleman: "devicon-middleman-plain",
  nanoc: "devicon-nanoc-plain",
  pelican: "devicon-pelican-plain",
  nikola: "devicon-nikola-plain",
  sphinx: "devicon-sphinx-plain",
  mkdocs: "devicon-mkdocs-plain",
  gitbook: "devicon-gitbook-plain",
  vuepress: "devicon-vuepress-plain",
  docsify: "devicon-docsify-plain",
  chakraui: "devicon-chakraui-plain",
  shadcn: "devicon-shadcn-plain",
};

export const techDescriptionMap: { [key: string]: string } = {
  javascript:
    "JavaScript is a powerful programming language used to create dynamic and interactive web experiences.",
  js: "JavaScript is a powerful programming language used to create dynamic and interactive web experiences.",
  typescript:
    "TypeScript is a typed superset of JavaScript that enhances code quality, scalability, and maintainability.",
  ts: "TypeScript is a typed superset of JavaScript that enhances code quality, scalability, and maintainability.",
  react:
    "React is a JavaScript library for building fast and interactive user interfaces using reusable components.",
  reactjs:
    "React.js is a JavaScript library for creating rich, component-based UIs efficiently.",
  nextjs:
    "Next.js is a React framework for building modern, server-rendered, and statically generated web applications.",
  next: "Next.js is a React framework that enables server-side rendering and static site generation.",
  nodejs:
    "Node.js is a JavaScript runtime built on Chrome's V8 engine, ideal for scalable server-side applications.",
  node: "Node.js is a JavaScript runtime for building fast, scalable backend services.",
  python:
    "Python is a versatile, beginner-friendly language widely used for web development, data science, and automation.",
  java: "Java is a robust, object-oriented programming language commonly used for enterprise and Android applications.",
  cpp: "C++ is a powerful language for system-level programming, games, and performance-critical software.",
  "c++":
    "C++ is a powerful language for system-level programming, games, and performance-critical software.",
  csharp:
    "C# is a modern, object-oriented language developed by Microsoft, widely used for Windows and game development.",
  "c#": "C# is a modern, object-oriented language developed by Microsoft, widely used for Windows and game development.",
  php: "PHP is a server-side scripting language used to build dynamic websites and web applications.",
  html: "HTML (HyperText Markup Language) is the standard language for structuring web pages and content.",
  css: "CSS (Cascading Style Sheets) is used to style and layout web pages with colors, fonts, and responsive designs.",
  tailwind:
    "Tailwind CSS is a utility-first CSS framework for rapidly building custom designs without leaving your HTML.",
  tailwindcss:
    "Tailwind CSS is a utility-first CSS framework that enables fast, consistent, and responsive UI development.",
  bootstrap:
    "Bootstrap is a popular front-end CSS framework for building responsive and mobile-first websites quickly.",
  git: "Git is a distributed version control system used to track changes and collaborate on code efficiently.",
  github:
    "GitHub is a platform for hosting and collaborating on Git repositories with version control and CI/CD tools.",
  docker:
    "Docker is a containerization platform that simplifies deploying and running applications across environments.",
  mongodb:
    "MongoDB is a NoSQL database that stores data in flexible, JSON-like documents for modern web applications.",
  mysql:
    "MySQL is a widely used open-source relational database for managing structured data efficiently.",
  postgresql:
    "PostgreSQL is a powerful open-source relational database with advanced features and strong SQL compliance.",
  firebase:
    "Firebase is a backend-as-a-service platform by Google that provides hosting, authentication, and databases.",
  graphql:
    "GraphQL is a query language for APIs that allows clients to request exactly the data they need.",
  vue: "Vue.js is a progressive JavaScript framework for building user interfaces with an approachable core library.",
  angular:
    "Angular is a TypeScript-based framework for building dynamic and scalable web applications.",
  redux:
    "Redux is a predictable state management library commonly used with React applications.",
  aws: "Amazon Web Services (AWS) is a leading cloud platform offering a wide range of on-demand computing services.",
  azure:
    "Microsoft Azure is a cloud computing platform offering services for deploying and managing applications.",
  gcp: "Google Cloud Platform (GCP) provides scalable infrastructure, AI, and cloud computing services.",
  linux:
    "Linux is an open-source operating system known for its stability, flexibility, and security.",
  figma:
    "Figma is a collaborative web-based design tool used for UI/UX design and prototyping.",
  photoshop:
    "Adobe Photoshop is a powerful graphic editing software used for image manipulation and digital design.",
  illustrator:
    "Adobe Illustrator is a vector graphics software used for logos, illustrations, and typography.",
  xd: "Adobe XD is a user experience design tool for creating wireframes and interactive prototypes.",
  premiere:
    "Adobe Premiere Pro is a professional video editing software used for creating and editing high-quality videos.",
  jest: "Jest is a JavaScript testing framework focused on simplicity and great developer experience.",
  cypress:
    "Cypress is a modern end-to-end testing framework for web applications, known for its developer-friendly tooling.",
  webpack:
    "Webpack is a module bundler that optimizes JavaScript and assets for modern web applications.",
  vite: "Vite is a lightning-fast frontend build tool for modern web projects using ES modules.",
  express:
    "Express.js is a minimal and flexible Node.js web application framework providing a strong set of features for APIs.",
  nestjs:
    "NestJS is a progressive Node.js framework for building efficient, scalable, and maintainable server-side applications.",
  django:
    "Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design.",
  flask:
    "Flask is a lightweight Python web framework ideal for building small to medium-sized web applications.",
  sass: "Sass is a CSS preprocessor that adds powerful features like variables, nesting, and mixins for cleaner styling.",
  less: "Less is a CSS preprocessor that extends CSS with variables, mixins, and functions for easier styling.",
  vitejs:
    "Vite is a next-generation, fast build tool for modern frontend development.",
  materialui:
    "Material UI is a React component library implementing Google’s Material Design system.",
  shadcn:
    "ShadCN/UI is a customizable component library for React and Next.js apps, built with Tailwind CSS.",
};
